Create Database waterAdventures;

create table userpass (
	username varchar(255),
	userpass varchar(20)
);


CREATE TABLE CLIENT
(
  CLIENT_ID INT NOT NULL,
    SINCE DATE NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  PRIMARY KEY (CLIENT_ID),
  UNIQUE (NAME)
);
Create table SERVICES (
    SERVICE_ID int Primary Key,
    SERVICE_Price float,
    SERVICE_Type varchar (255),
    SERVICE_Name varchar (255)
       );

CREATE TABLE USERADDRESS
(
  NAME VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  CLIENT_ID INT NOT NULL,
  DATE_OF_JOINING DATE NOT NULL,
  PHONE INT NOT NULL,
  EMAILID VARCHAR(20) NOT NULL,
  PRIMARY KEY (CLIENT_ID),
  UNIQUE (NAME),
  UNIQUE (PHONE)
  );


CREATE TABLE QUOTE
(
  PRICE INT NOT NULL,
  SERVICE_ID INT NOT NULL,
  QUOTE_ID INT NOT NULL,
   CLIENT_ID INT NOT NULL,
  PRIMARY KEY (QUOTE_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)  ON DELETE CASCADE,
	FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(SERVICE_ID)  ON DELETE CASCADE

);



